/**
 * Starlink 地面站（Gateway）名称映射
 * 将英文城市/州名转换为中文名称
 */

// Auto-generated mapping for Starlink Gateway names to Chinese
export const gatewayNameMapping = {
  "Lekki, NG": "尼日利亚, Lekki",
  "Ikire, NG": "尼日利亚, Ikire",
  "Nairobi, KE - Cabanas | Mega": "KE - CABANAS, Nairobi",
  "Okun Ajah (Lagos), NG | Mega": "尼日利亚, Okun Ajah (Lagos)",
  "Sagamu, Ogun, NG": "尼日利亚, Sagamu",
  "Port Harrcourt, Rivers, NG": "尼日利亚, Port Harrcourt",
  "Matola, MZ | Mega": "莫桑比克, Matola",
  "Gaborone, BW | Mega": "BW, Gaborone",
  "Lobatse, BW | Mega": "BW, Lobatse",
  "Thika, KE | Mega": "肯尼亚, Thika",
  "Kigali, RW": "卢旺达, Kigali",
  "Akita, JP": "日本, Akita",
  "Hitachinaka, JP": "日本, Hitachinaka",
  "Otaru, JP": "日本, Otaru",
  "Yamaguchi, JP": "日本, Yamaguchi",
  "Suva, FJ": "斐济, Suva",
  "Awarua, NZ": "新西兰, Awarua",
  "Cromwell, NZ": "新西兰, Cromwell",
  "Hinds, NZ": "新西兰, Hinds",
  "Cleavdon, NZ": "新西兰, Cleavdon",
  "Te Hana, NZ": "新西兰, Te Hana",
  "Puwera, NZ": "新西兰, Puwera",
  "Toonpan, QLD, AU": "澳大利亚, 昆士兰州, Toonpan",
  "Willows. QLD, AU": "澳大利亚, Willows. QLD",
  "Pimba, SA, AU (GSN#3023)": "AU (GSN#3023), Pimba",
  "Boorowa, NSW, AU (GSN#55)": "AU (GSN#55), Boorowa",
  "Wagin, WA, AU (GSN#3002)": "AU (GSN#3002), Wagin",
  "Calrossie, NSW, AU": "澳大利亚, 新南威尔士州, Calrossie",
  "Merredin, WA, AU": "澳大利亚, 西澳大利亚州, Merredin",
  "Cataby, WA, AU": "澳大利亚, 西澳大利亚州, Cataby",
  "Ki Ki, SA, AU": "澳大利亚, 南澳大利亚州, Ki Ki",
  "Torrumbarry, VIC, AU": "澳大利亚, 维多利亚州, Torrumbarry",
  "Cobargo, NSW, AU": "澳大利亚, 新南威尔士州, Cobargo",
  "Bogantungan, QLD, AU": "澳大利亚, 昆士兰州, Bogantungan",
  "Springbrook Creek, NSW, AU": "澳大利亚, 新南威尔士州, Springbrook Creek",
  "Bulla Bulling, WA, AU": "澳大利亚, 西澳大利亚州, Bulla Bulling",
  "Canyonleigh, NSW, AU | Mega": "澳大利亚, 新南威尔士州, Canyonleigh",
  "Tea Gardens, NSW, AU": "澳大利亚, 新南威尔士州, Tea Gardens",
  "Warra, QLD, AU": "澳大利亚, 昆士兰州, Warra",
  "Sellheim, QLD, AU": "澳大利亚, 昆士兰州, Sellheim",
  "Angeles, PH": "菲律宾, Angeles",
  "Kendari, ID": "美国, 爱达荷州, Kendari",
  "Anakie, VIC, AU": "澳大利亚, 维多利亚州, Anakie",
  "Koonwarra, VIC, AU": "澳大利亚, 维多利亚州, Koonwarra",
  "Nabiac, NSW, AU | Mega": "澳大利亚, 新南威尔士州, Nabiac",
  "Bathurst, NSW, AU | Mega": "澳大利亚, 新南威尔士州, Bathurst",
  "Majura, ACT, AU | Mega": "澳大利亚, 澳大利亚首都领地, Majura",
  "Singapore, SG | Mega": "新加坡, Singapore",
  "Awaura, NZ - TT&C (AW1)": "NZ - TT&C (AW1), Awaura",
  "Broken Hill, NSW, AU (GSN#56)": "AU (GSN#56), Broken Hill",
  "Petra Jaya, MY": "马来西亚, Petra Jaya",
  "Cikarang Barat, ID - Almat GW | Mega": "ID - ALMAT GW, Cikarang Barat",
  "Palangka Raya, ID": "美国, 爱达荷州, Palangka Raya",
  "Macquarie Park, NSW, AU | Mega": "澳大利亚, 新南威尔士州, Macquarie Park",
  "Augusta, WA, AU": "澳大利亚, 西澳大利亚州, Augusta",
  "Merredin, WA, AU | Mega": "澳大利亚, 西澳大利亚州, Merredin",
  "Terang, VIC, AU | Mega": "澳大利亚, 维多利亚州, Terang",
  "Sale, VIC, AU | Mega": "澳大利亚, 维多利亚州, Sale",
  "Inglewood, QLD, AU | Mega": "澳大利亚, 昆士兰州, Inglewood",
  "Ningi, QLD, AU | Mega": "澳大利亚, 昆士兰州, Ningi",
  "Harvey, WA, AU | Mega": "澳大利亚, 西澳大利亚州, Harvey",
  "Malaga, WA, AU | Mega": "澳大利亚, 西澳大利亚州, Malaga",
  "Darwin, NT, AU | Mega": "澳大利亚, 北领地, Darwin",
  "Kiara, WA, AU | E-band only": "澳大利亚, 西澳大利亚州, Kiara",
  "Harristown, QLD, AU | Mega": "澳大利亚, 昆士兰州, Harristown",
  "Nueva Vizcaya (Province), PH": "菲律宾, Nueva Vizcaya (Province)",
  "Quezon (province), PH": "菲律宾, Quezon (province)",
  "Cebu(?), PH": "菲律宾, Cebu(?)",
  "Kuala Lumpur(?), MY": "马来西亚, Kuala Lumpur(?)",
  "Mumbai, IN": "美国, 印第安纳州, Mumbai",
  "Pune, IN": "美国, 印第安纳州, Pune",
  "Indore, IN": "美国, 印第安纳州, Indore",
  "Cleavedon, NZ | Mega": "新西兰, Cleavedon",
  "Te Hana, NZ | Mega": "新西兰, Te Hana",
  "Da Nang, VT": "美国, 佛蒙特州, Da Nang",
  "West Footscray, VIC, AU | Mega": "澳大利亚, 维多利亚州, West Footscray",
  "Gazipur, BD | Mega": "孟加拉国, Gazipur",
  "Rajshahi, BD | Mega": "孟加拉国, Rajshahi",
  "Jashore, BD": "孟加拉国, Jashore",
  "Betbunia(?), BD": "孟加拉国, Betbunia(?)",
  "Ho Chi Minh - Hi-Tech Park, VT": "美国, 佛蒙特州, Ho Chi Minh - Hi-Tech Park",
  "Ho Chi Minh - Tan Huan, VT": "美国, 佛蒙特州, Ho Chi Minh - Tan Huan",
  "Makassar, ID": "美国, 爱达荷州, Makassar",
  "Warragul, VIC, AU | E-only": "澳大利亚, 维多利亚州, Warragul",
  "Kilmore, VIC, AU | E-only - Ogradys Road GW": "澳大利亚, 维多利亚州, Kilmore",
  "Hume, ACT, AU | E-only - Raws Crescent GW": "澳大利亚, 澳大利亚首都领地, Hume",
  "Macquire Park, NSW, AU | Mega": "澳大利亚, 新南威尔士州, Macquire Park",
  "Navi Mumbai, IN": "美国, 印第安纳州, Navi Mumbai",
  "Noida, IN": "美国, 印第安纳州, Noida",
  "Chennai, IN": "美国, 印第安纳州, Chennai",
  "Waipara, NZ | Mega": "新西兰, Waipara",
  "Woodville, NZ | Mega": "新西兰, Woodville",
  "Te Kuiti, NZ | Mega": "新西兰, Te Kuiti",
  "Christchurch, NZ | Mega": "新西兰, Christchurch",
  "Savanna, OK | Mega": "美国, 俄克拉荷马州, Savanna",
  "Savannah, TN | Mega": "美国, 田纳西州, Savannah",
  "York, PA | Mega": "美国, 宾夕法尼亚州, York",
  "Debeque, CO | Mega": "美国, 科罗拉多州, Debeque",
  "Baxley, GA / Surrency, GA | Mega": "美国, 佐治亚州, Baxley",
  "Hillsboro, TX | Mega": "美国, 德克萨斯州, Hillsboro",
  "Marshall, TX | Mega": "美国, 德克萨斯州, Marshall",
  "Prosser, WA | Mega": "美国, 华盛顿州, Prosser",
  "Redmond, WA | Mega": "美国, 华盛顿州, Redmond",
  "Arlington, OR | Mega": "美国, 俄勒冈州, Arlington",
  "Blountsville, AL | Mega": "美国, 阿拉巴马州, Blountsville",
  "Angola, IN | Mega": "美国, 印第安纳州, Angola",
  "Des Moines, NM | Mega": "美国, 新墨西哥州, Des Moines",
  "Brunswick, ME | Mega": "美国, 缅因州, Brunswick",
  "Romulus, NY | Mega": "美国, 纽约州, Romulus",
  "Roberts, WI | Mega": "美国, 威斯康星州, Roberts",
  "Mt Ayr, IN | Mega": "美国, 印第安纳州, Mt Ayr",
  "Inman, KS | Mega": "美国, 堪萨斯州, Inman",
  "Kenansville, FL | Mega": "美国, 佛罗里达州, Kenansville",
  "Arvin, CA | Mega": "美国, 加利福尼亚州, Arvin",
  "Elkton, MD | Mega": "美国, 马里兰州, Elkton",
  "Anderson, SC | Mega": "美国, 南卡罗来纳州, Anderson",
  "Port Matilda, PA | Mega": "美国, 宾夕法尼亚州, Port Matilda",
  "Sheffield, IL | Mega": "美国, 伊利诺伊州, Sheffield",
  "Clinton, IL | Mega": "美国, 伊利诺伊州, Clinton",
  "Charleston, OR / Bandon, OR | Mega": "美国, 俄勒冈州, Charleston",
  "New Braunfels, TX | Mega": "美国, 德克萨斯州, New Braunfels",
  "Tionesta, CA / Tulake, CA": "美国, 加利福尼亚州, Tionesta",
  "Benkelman, NE | Mega": "美国, 内布拉斯加州, Benkelman",
  "Sunset, TX | E-Band": "美国, 德克萨斯州, Sunset",
  "Phoenix, AZ | E-Band": "美国, 亚利桑那州, Phoenix",
  "Corpus Christi, TX | Mega": "美国, 德克萨斯州, Corpus Christi",
  "Salem, OR | E-Band": "美国, 俄勒冈州, Salem",
  "Kiowa, CO | E-Band": "美国, 科罗拉多州, Kiowa",
  "Piscataway, NJ | E-Band": "美国, 新泽西州, Piscataway",
  "Pine Valley, CA | E-Band": "美国, 加利福尼亚州, Pine Valley",
  "Chico, CA | Mega": "美国, 加利福尼亚州, Chico",
  "Niland, CA | Mega": "美国, 加利福尼亚州, Niland",
  "Cal-Nev-Air, NV | E-Band": "美国, 内华达州, Cal-Nev-Air",
  "Hawthorne, CA #2": "CA #2, Hawthorne",
  "Olympia, WA": "美国, 华盛顿州, Olympia",
  "Richardson, TX": "美国, 德克萨斯州, Richardson",
  "Fort Lauderdale, FL": "美国, 佛罗里达州, Fort Lauderdale",
  "Norcross, GA": "美国, 佐治亚州, Norcross",
  "Anchorage, AK": "美国, 阿拉斯加州, Anchorage",
  "The Dalles, OR": "美国, 俄勒冈州, The Dalles",
  "Charleston, SC": "美国, 南卡罗来纳州, Charleston",
  "Columbus, OH": "美国, 俄亥俄州, Columbus",
  "Tumon, GU": "关岛, Tumon",
  "Molokai, HI": "美国, 夏威夷州, Molokai",
  "Arbuckle, CA": "美国, 加利福尼亚州, Arbuckle",
  "Springer, OK": "美国, 俄克拉荷马州, Springer",
  "Robertsdale, AL": "美国, 阿拉巴马州, Robertsdale",
  "Tracy City, TN": "美国, 田纳西州, Tracy City",
  "Gaffney, SC": "美国, 南卡罗来纳州, Gaffney",
  "North Bend, WA": "美国, 华盛顿州, North Bend",
  "Des Moines, IA": "美国, 爱荷华州, Des Moines",
  "Cheyenne, WY": "美国, 怀俄明州, Cheyenne",
  "Quincy, WA": "美国, 华盛顿州, Quincy",
  "San Antonio, TX": "美国, 德克萨斯州, San Antonio",
  "Llano Grande, MX": "墨西哥, Llano Grande",
  "Tapachula, MX": "墨西哥, Tapachula",
  "Merida, MX": "墨西哥, Merida",
  "Peñuelas, MX": "墨西哥, Peñuelas",
  "Cabo San Lucas, MX": "墨西哥, Cabo San Lucas",
  "Charcas, MX": "墨西哥, Charcas",
  "El Marques, MX": "墨西哥, El Marques",
  "Monterey, MX": "墨西哥, Monterey",
  "Mazahua, MX": "墨西哥, Mazahua",
  "Lockport, NY": "美国, 纽约州, Lockport",
  "Kuparuk, AK": "美国, 阿拉斯加州, Kuparuk",
  "Ponce, PR": "波多黎各, Ponce",
  "Hawthorne, CA": "美国, 加利福尼亚州, Hawthorne",
  "McGregor, TX": "美国, 德克萨斯州, McGregor",
  "Boca Chica, TX": "美国, 德克萨斯州, Boca Chica",
  "Fairbanks, AK": "美国, 阿拉斯加州, Fairbanks",
  "Bellingham, WA": "美国, 华盛顿州, Bellingham",
  "Greenville, PA": "美国, 宾夕法尼亚州, Greenville",
  "Merrillan, WI": "美国, 威斯康星州, Merrillan",
  "Conrad, MT": "美国, 蒙大拿州, Conrad",
  "Butte, MT": "美国, 蒙大拿州, Butte",
  "Roll, AZ": "美国, 亚利桑那州, Roll",
  "Colburn, ID": "美国, 爱达荷州, Colburn",
  "Litchfield CT": "Litchfield CT",
  "Evanston, WY": "美国, 怀俄明州, Evanston",
  "Santiago de los Caballeros, DO": "多米尼加, Santiago de los Caballeros",
  "Lawrence, KS": "美国, 堪萨斯州, Lawrence",
  "Loring, ME": "美国, 缅因州, Loring",
  "Kalama, WA": "美国, 华盛顿州, Kalama",
  "Beekmantown, NY": "美国, 纽约州, Beekmantown",
  "Panaca, NV": "美国, 内华达州, Panaca",
  "Warren, MO": "美国, 密苏里州, Warren",
  "Nemaha, NE": "美国, 内布拉斯加州, Nemaha",
  "Manistique, MI": "美国, 密歇根州, Manistique",
  "Slope County, ND": "美国, 北达科他州, Slope County",
  "Cass County, ND": "美国, 北达科他州, Cass County",
  "Sanderson TX": "Sanderson TX",
  "Hitterdal, MN": "美国, 明尼苏达州, Hitterdal",
  "Vernon, UT": "美国, 犹他州, Vernon",
  "Punta Gorda, FL": "美国, 佛罗里达州, Punta Gorda",
  "Dumas, TX": "美国, 德克萨斯州, Dumas",
  "Mandale, NC": "美国, 北卡罗来纳州, Mandale",
  "Robbins, CA": "美国, 加利福尼亚州, Robbins",
  "Wise, NC": "美国, 北卡罗来纳州, Wise",
  "Hamshire, TX": "美国, 德克萨斯州, Hamshire",
  "Marcell, MN": "美国, 明尼苏达州, Marcell",
  "Hillman, MI": "美国, 密歇根州, Hillman",
  "Broadview, IL": "美国, 伊利诺伊州, Broadview",
  "Lunenberg, VT": "美国, 佛蒙特州, Lunenberg",
  "Sullivan, ME": "美国, 缅因州, Sullivan",
  "Rolette, ND": "美国, 北达科他州, Rolette",
  "Ketchikan, AK": "美国, 阿拉斯加州, Ketchikan",
  "Nome, AK": "美国, 阿拉斯加州, Nome",
  "Elbert, CO": "美国, 科罗拉多州, Elbert",
  "Frederick, MD": "美国, 马里兰州, Frederick",
  "Murrieta, CA": "美国, 加利福尼亚州, Murrieta",
  "Boydton, VA": "美国, 弗吉尼亚州, Boydton",
  "Wichita Falls, TX": "美国, 德克萨斯州, Wichita Falls",
  "Caleta, DO": "多米尼加, Caleta",
  "Marathon, ON, CA (GSN-19)": "CA (GSN-19), Marathon",
  "Saguenay, QC, CA": "美国, 加利福尼亚州, Saguenay",
  "Sambro Creek, NS, CA (GSN-21)": "CA (GSN-21), Sambro Creek",
  "Toa Baja, PR": "波多黎各, Toa Baja",
  "Adelanto, CA | E-band": "美国, 加利福尼亚州, Adelanto",
  "St Johns, NL, CA": "美国, 加利福尼亚州, St Johns",
  "West Jordan, UT": "美国, 犹他州, West Jordan",
  "Perry, FL": "美国, 佛罗里达州, Perry",
  "Dubuque, IA": "美国, 爱荷华州, Dubuque",
  "Willemstad, CW": "库拉索, Willemstad",
  "Oistins, BB": "巴巴多斯, Oistins",
  "Seatle, WA - The Emerald City GW": "WA - THE EMERALD CITY GW, Seatle",
  "Centennial, CO - The Centennial GW,": ", Centennial",
  "Denver, CO - Iron Mountain GW": "CO - IRON MOUNTAIN GW, Denver",
  "Phoenix, AZ - The X GW": "AZ - THE X GW, Phoenix",
  "Atlanta, GA - The Hotlanta GW": "GA - THE HOTLANTA GW, Atlanta",
  "Goodyear, AZ - Estrella Mountain GW": "AZ - ESTRELLA MOUNTAIN GW, Goodyear",
  "Lisle, IL - The ChiTown GW": "IL - THE CHITOWN GW, Lisle",
  "Westbury NY - Take Me Home GW": "Westbury NY - Take Me Home GW",
  "Minneapolis, MN - Winter is Coming GW": "MN - WINTER IS COMING GW, Minneapolis",
  "Ft Lauderdale, FL - Miami Sloth GW": "FL - MIAMI SLOTH GW, Ft Lauderdale",
  "Highland Ranch, CO - Highlands Ranch GW": "CO - HIGHLANDS RANCH GW, Highland Ranch",
  "Egan, MN - The Boiler Room GW": "MN - THE BOILER ROOM GW, Egan",
  "Los Angeles, CA - Anotha One' in GW": "CA - ANOTHA ONE' IN GW, Los Angeles",
  "Shakopee, MN - The Let's Goooo GW": "MN - THE LET'S GOOOO GW, Shakopee",
  "Lindon, UT - The Gong GW": "UT - THE GONG GW, Lindon",
  "Richardson, TX - The Name Loading GW": "TX - THE NAME LOADING GW, Richardson",
  "Denver, CO - The LLAF GW": "CO - THE LLAF GW, Denver",
  "Santa Clara, CA - The Bang Bang Niner GW": "CA - THE BANG BANG NINER GW, Santa Clara",
  "Fair Park, UT - The This is Fine GW": "UT - THE THIS IS FINE GW, Fair Park",
  "New York, NY - The Shea GW": "NY - THE SHEA GW, New York",
  "Chaska, MN - The Sad Saturday GW": "MN - THE SAD SATURDAY GW, Chaska",
  "West Jordan, UT - The Eye of Sauron GW": "UT - THE EYE OF SAURON GW, West Jordan",
  "Dallas, TX - Da PoP GW": "TX - DA POP GW, Dallas",
  "Broadview, IL - The fr fr GW": "IL - THE FR FR GW, Broadview",
  "Brooklyn Park, MN - The Purple Rain GW": "MN - THE PURPLE RAIN GW, Brooklyn Park",
  "Ashland, IL - The Sea Monkey GW": "IL - THE SEA MONKEY GW, Ashland",
  "Sterling, VA - The Schedule Chicken GW": "VA - THE SCHEDULE CHICKEN GW, Sterling",
  "Kauai, HI - I am McLovin GW": "HI - I AM MCLOVIN GW, Kauai",
  "Douglas, WY - I'm a Business, Man GW": "MAN GW, Douglas",
  "Wellington, VA - East Coast Bestest GW": "VA - EAST COAST BESTEST GW, Wellington",
  "Villahermosa, MX": "墨西哥, Villahermosa",
  "Calverton, NY - Earth Go Hard GW": "NY - EARTH GO HARD GW, Calverton",
  "Lynnwood, WA - Mountain is Out GW": "WA - MOUNTAIN IS OUT GW, Lynnwood",
  "Seattle, WA -The Kremwerk GW": "WA -THE KREMWERK GW, Seattle",
  "Los Angeles, CA - The Lebron GW": "CA - THE LEBRON GW, Los Angeles",
  "Los Angeles, CA - Yet Another HT GW": "CA - YET ANOTHER HT GW, Los Angeles",
  "Dallas, TX - The Mavs GW": "TX - THE MAVS GW, Dallas",
  "Roll, AZ - They See Me Rollin GW": "AZ - THEY SEE ME ROLLIN GW, Roll",
  "Lithia Springs, GA - The Georgia Peaches GW": "GA - THE GEORGIA PEACHES GW, Lithia Springs",
  "Vernon, UT - The Pain Train GW": "UT - THE PAIN TRAIN GW, Vernon",
  "Evanston, WY - The Thou Shall Not Pass GW": "WY - THE THOU SHALL NOT PASS GW, Evanston",
  "Pott’s Junction, GU - The Katu Gato Community GW": "GU - THE KATU GATO COMMUNITY GW, Pott’s Junction",
  "Atlanta, GA - The Georgia Powerhouse GW": "GA - THE GEORGIA POWERHOUSE GW, Atlanta",
  "Ashburn, VA - The Greedy Tortoise GW": "VA - THE GREEDY TORTOISE GW, Ashburn",
  "Grant District, WV - The Huntin Wabbits GW": "WV - THE HUNTIN WABBITS GW, Grant District",
  "Sandston, VA - The Homie Keith GW": "VA - THE HOMIE KEITH GW, Sandston",
  "Akron, OH - The All Gas No Brakes GW": "OH - THE ALL GAS NO BRAKES GW, Akron",
  "Myrtle Beach, SC - The Gone Golfing GW": "SC - THE GONE GOLFING GW, Myrtle Beach",
  "San Jose, CA - The Walsh GW": "CA - THE WALSH GW, San Jose",
  "Tucson, AZ - The Bear Down GW": "AZ - THE BEAR DOWN GW, Tucson",
  "Hawkins, TX - The Hawkins GW": "TX - THE HAWKINS GW, Hawkins",
  "Thomaston, GA - The Blitz GW": "GA - THE BLITZ GW, Thomaston",
  "Virginia Beach, VA - The Lil b GW": "VA - THE LIL B GW, Virginia Beach",
  "North Miami, FL - The United Teleports GW": "FL - THE UNITED TELEPORTS GW, North Miami",
  "Burbank, CA - The West Coast Best Coast GW": "CA - THE WEST COAST BEST COAST GW, Burbank",
  "Port St. Lucie, FL - The PSL GW": "FL - THE PSL GW, Port St. Lucie",
  "Gordon, GA - The Power Lines GW": "GA - THE POWER LINES GW, Gordon",
  "Secaucus, NJ - The DAVI GW": "NJ - THE DAVI GW, Secaucus",
  "Mesa, AZ - The Booker GW": "AZ - THE BOOKER GW, Mesa",
  "Bluffdale, UT - The Bonanza Express GW": "UT - THE BONANZA EXPRESS GW, Bluffdale",
  "Howell, UT - The Full Send GW": "UT - THE FULL SEND GW, Howell",
  "Wellington, UT - The Utah Jazz GW": "UT - THE UTAH JAZZ GW, Wellington",
  "Delta, UT - The Cosmic Ray GW": "UT - THE COSMIC RAY GW, Delta",
  "New York, NY - The New York, New Me GW": "NEW ME GW, New York",
  "New York, NY - The Slice Slice Baby GW": "NY - THE SLICE SLICE BABY GW, New York",
  "Los Angeles, CA - The Send it! GW": "CA - THE SEND IT! GW, Los Angeles",
  "Marathon, FL - The Florida Keys GW": "FL - THE FLORIDA KEYS GW, Marathon",
  "Chattanooga, TN - The Shady’s Corner GW": "TN - THE SHADY’S CORNER GW, Chattanooga",
  "Wise, VA - The Wise GW": "VA - THE WISE GW, Wise",
  "Oxford, AL - The Super Speedway GW": "AL - THE SUPER SPEEDWAY GW, Oxford",
  "Miami, FL - ULTRA Are You Ready GW": "FL - ULTRA ARE YOU READY GW, Miami",
  "Tukwila, WA - The Tukwila Gateway": "WA - THE TUKWILA GATEWAY, Tukwila",
  "Bellingham, WA - The Bellingham GW": "WA - THE BELLINGHAM GW, Bellingham",
  "Fremont, CA - The Plaid Mode GW": "CA - THE PLAID MODE GW, Fremont",
  "Punta Gorda, FL - The Florida Man GW": "FL - THE FLORIDA MAN GW, Punta Gorda",
  "Conrad, MT - The Rad GW": "MT - THE RAD GW, Conrad",
  "Butte, MT - The Butte GW": "MT - THE BUTTE GW, Butte",
  "Boise, ID - The Boise GW": "ID - THE BOISE GW, Boise",
  "Dubois, ID - The InRange GW": "ID - THE INRANGE GW, Dubois",
  "Duluth, MN - The Superior GW": "MN - THE SUPERIOR GW, Duluth",
  "Milwaukee, WI - The Cheese Head GW": "WI - THE CHEESE HEAD GW, Milwaukee",
  "Bridgewater, CT - The Algo of Power GW": "CT - THE ALGO OF POWER GW, Bridgewater",
  "Edison, NJ - The Midnight Cowboy GW": "NJ - THE MIDNIGHT COWBOY GW, Edison",
  "Cheyenne, WY - The Lunavi GW": "WY - THE LUNAVI GW, Cheyenne",
  "Elbert, CO - Untz Untz GW": "CO - UNTZ UNTZ GW, Elbert",
  "Watkins, CO - The Solar GW": "CO - THE SOLAR GW, Watkins",
  "Irvine, CA - The Zot! Zot! Zot! GW": "CA - THE ZOT! ZOT! ZOT! GW, Irvine",
  "Madera, CA - The Madera GW": "CA - THE MADERA GW, Madera",
  "Boca Chica, TX - Stargate GW": "TX - STARGATE GW, Boca Chica",
  "Queretaro, MX | Mega": "墨西哥, Queretaro",
  "Boucherville, QC, CA - Boucherville GW": "CA - BOUCHERVILLE GW, Boucherville",
  "Kahnawake, QC, CA - Kahanawake GW": "CA - KAHANAWAKE GW, Kahnawake",
  "Apple Hill, ON, CA - Apple Hill GW": "CA - APPLE HILL GW, Apple Hill",
  "Beekmantown, NY - Little GW That Could | Mega": "NY - LITTLE GW THAT COULD, Beekmantown",
  "Anchorage, AK - Great Alaskan GW": "AK - GREAT ALASKAN GW, Anchorage",
  "Dallas, TX - The First Rodeo | Mega": "TX - THE FIRST RODEO, Dallas",
  "Atlanta, GA - Ponce City Market GW": "GA - PONCE CITY MARKET GW, Atlanta",
  "Watonwan, MN - the La Salle GW | Mega": "MN - THE LA SALLE GW, Watonwan",
  "Atlanta, GA - The Edged ATL1 GW": "GA - THE EDGED ATL1 GW, Atlanta",
  "North Kansas City, MO - The BBQ GW": "MO - THE BBQ GW, North Kansas City",
  "Flushing NY - The Game Set Match GW": "Flushing NY - The Game Set Match GW",
  "Brewster, WA - TT&C (BR1)": "WA - TT&C (BR1), Brewster",
  "Staten Island, NY - The Staten Island GW": "NY - THE STATEN ISLAND GW, Staten Island",
  "Sainte-Catherine, QC, CA": "美国, 加利福尼亚州, Sainte-Catherine",
  "Vandenberg CA, US - The \"Vandenberg AFB\" GW": "US - THE \"VANDENBERG AFB\" GW, Vandenberg CA",
  "Markham, ON, CA - Centersquare GW": "CA - CENTERSQUARE GW, Markham",
  "Brooks, AB, CA": "美国, 加利福尼亚州, Brooks",
  "Crossfield, AB, CA": "美国, 加利福尼亚州, Crossfield",
  "Edmonton, AB, CA - Edmonton GW": "CA - EDMONTON GW, Edmonton",
  "Calgary, AB, CA - Balzac GW": "CA - BALZAC GW, Calgary",
  "Calgary, AB, CA - Janet GW": "CA - JANET GW, Calgary",
  "Strathmore, AB, CA - Strathmore GW": "CA - STRATHMORE GW, Strathmore",
  "Seattle, WA - Seattle Freeze GW": "WA - SEATTLE FREEZE GW, Seattle",
  "Camaçari, BR": "巴西, Camaçari",
  "Guarapari, BR": "巴西, Guarapari",
  "Itaboraí, BR": "巴西, Itaboraí",
  "João Câmara, BR": "巴西, João Câmara",
  "Luz, BR": "巴西, Luz",
  "Montes Carlos, BR": "巴西, Montes Carlos",
  "Mossoró, BR": "巴西, Mossoró",
  "Passa Quatro, BR": "巴西, Passa Quatro",
  "Porto Alegre, BR": "巴西, Porto Alegre",
  "Presidente Prudente, BR": "巴西, Presidente Prudente",
  "Rio Negro, BR": "巴西, Rio Negro",
  "Santana de Parnaíba, BR": "巴西, Santana de Parnaíba",
  "São Gonçalo do Amarante, BR": "巴西, São Gonçalo do Amarante",
  "Surubim, BR": "巴西, Surubim",
  "Uruguaiana, BR": "巴西, Uruguaiana",
  "Manaus, BR": "巴西, Manaus",
  "Aracaju, BR": "巴西, Aracaju",
  "Rio de Janeiro, BR": "巴西, Rio de Janeiro",
  "Osasco, BR | Mega": "巴西, Osasco",
  "Rolândia, BR": "巴西, Rolândia",
  "Fortaleza, BR | Mega": "巴西, Fortaleza",
  "Juazeiro do Norte. BR": "Juazeiro do Norte. BR",
  "Nova Santa Rita, BR": "巴西, Nova Santa Rita",
  "Vinhedo, BR": "巴西, Vinhedo",
  "Imperatriz, BR | Mega": "巴西, Imperatriz",
  "Benevides, BR | Mega": "巴西, Benevides",
  "Itaitinga, BR | Mega": "巴西, Itaitinga",
  "Lauro de Freitas, BR | Mega": "巴西, Lauro de Freitas",
  "Barreira, BR | Mega": "巴西, Barreira",
  "Caucaia, BR | Mega": "巴西, Caucaia",
  "Brasília, BR": "巴西, Brasília",
  "Quixadá, BR": "巴西, Quixadá",
  "Cuiabá, BR": "巴西, Cuiabá",
  "Fortaleza-2, BR": "巴西, Fortaleza-2",
  "Puerto Montt, CL": "智利, Puerto Montt",
  "Puerto Saavedra, CL": "智利, Puerto Saavedra",
  "San Clemente, CL": "智利, San Clemente",
  "Santa Elena, CL": "智利, Santa Elena",
  "Caldera, CL": "智利, Caldera",
  "Noviciado, CL": "智利, Noviciado",
  "Punta Arenas, CL": "智利, Punta Arenas",
  "Medellin(?), CO": "美国, 科罗拉多州, Medellin(?)",
  "Falda del Carmen (Cordoba), AR": "美国, 阿肯色州, Falda del Carmen (Cordoba)",
  "La Plata, Buenos Aires, AR": "美国, 阿肯色州, La Plata",
  "Campana, Buenos Aires, AR": "美国, 阿肯色州, Campana",
  "Rio Negro, AR": "美国, 阿肯色州, Rio Negro",
  "Salta, AR": "美国, 阿肯色州, Salta",
  "Chivilcoy, Buenos Aires, AR": "美国, 阿肯色州, Chivilcoy",
  "Mendoza, AR | Mega": "美国, 阿肯色州, Mendoza",
  "Buenos Aires-Technopolis, AR | Mega": "美国, 阿肯色州, Buenos Aires-Technopolis",
  "Bogota, CO": "美国, 科罗拉多州, Bogota",
  "Lima-2, PE": "秘鲁, Lima-2",
  "Aquierpa, PE | Mega": "秘鲁, Aquierpa",
  "Piura, PE | Mega": "秘鲁, Piura",
  "San Bernardo, CL | Mega": "智利, San Bernardo",
  "Limache, CL | Mega": "智利, Limache",
  "Las Condes, CL | Mega": "智利, Las Condes",
  "Quilicura, CL | Mega": "智利, Quilicura",
  "Cabrero, CL | Mega": "智利, Cabrero",
  "Unalaska, AK, US": "美国, 阿拉斯加州, Unalaska",
  "Iqualuit, NU, CA": "美国, 加利福尼亚州, Iqualuit",
  "Nauru, NR": "瑙鲁, Nauru",
  "Cape Canaveral, FL, US - The Full Send GW": "US - THE FULL SEND GW, Cape Canaveral",
  "Brucejack, BC, CA": "美国, 加利福尼亚州, Brucejack",
  "Lihir, PG": "巴布亚新几内亚, Lihir",
  "Kuujjuaq, QC, CA": "美国, 加利福尼亚州, Kuujjuaq",
  "Krosrae, Micronesia": "MICRONESIA, Krosrae",
  "Tawara Is, Kiribati": "KIRIBATI, Tawara Is",
  "Tuvalu, TV": "图瓦卢, Tuvalu",
  "Galapagos, EC": "厄瓜多尔, Galapagos",
  "Blue City, OM": "阿曼, Blue City",
  "Blue City, OM | Mega expansion": "阿曼, Blue City",
  "Umm Qarn, QA | Mega": "卡塔尔, Umm Qarn",
  "Garrettstown, IE": "爱尔兰, Garrettstown",
  "Elfordstown, IE": "爱尔兰, Elfordstown",
  "Isle of Man, UK": "UK, Isle of Man",
  "Goonhilly, UK": "UK, Goonhilly",
  "Chalfont Grove, UK": "UK, Chalfont Grove",
  "Wherstead, UK": "UK, Wherstead",
  "Hoo, UK": "UK, Hoo",
  "Woodwalton, UK": "UK, Woodwalton",
  "Morn Hill, UK": "UK, Morn Hill",
  "Fawley, UK": "UK, Fawley",
  "Bristol, UK": "UK, Bristol",
  "Isle of Man, UK | Mega": "UK, Isle of Man",
  "Villenave d’Ornon, FR": "法国, Villenave d’Ornon",
  "Lepe, ES": "西班牙, Lepe",
  "Villarejo de Salvanes, ES": "西班牙, Villarejo de Salvanes",
  "Ibi, ES": "西班牙, Ibi",
  "Marsala, IT": "意大利, Marsala",
  "Foggia, IT": "意大利, Foggia",
  "Villamaggiore, IT": "意大利, Villamaggiore",
  "Frankfurt, DE": "美国, 特拉华州, Frankfurt",
  "Aerzen, DE": "美国, 特拉华州, Aerzen",
  "Wola Krobowska, PL": "波兰, Wola Krobowska",
  "Kaunas, LT": "立陶宛, Kaunas",
  "Muallim, TR": "土耳其, Muallim",
  "Covilha, PT": "葡萄牙, Covilha",
  "Hoofddorp, NL (GSN#105)": "NL (GSN#105), Hoofddorp",
  "Plana, BG": "保加利亚, Plana",
  "Stolnik, BG | Mega": "保加利亚, Stolnik",
  "Sofia, BG": "保加利亚, Sofia",
  "Loeches (Madrid), ES | Mega": "西班牙, Loeches (Madrid)",
  "Santa Olalla, ES": "西班牙, Santa Olalla",
  "Gelida, ES": "西班牙, Gelida",
  "Aflenz, OS | Mega": "OS, Aflenz",
  "Leuk, CH": "瑞士, Leuk",
  "Killala, IE": "爱尔兰, Killala",
  "Tromsø, NO - TT&C (TR1)": "NO - TT&C (TR1), Tromsø",
  "Villamaggiore-2, IT | Mega expansion": "意大利, Villamaggiore-2"
};

/**
 * 解析地面站名称并返回中文名称
 * 优先从 gatewayNameMapping 查找完全匹配
 * 
 * @param {string} name - 英文名称
 * @returns {string} 中文名称
 */
export function getChineseGatewayName(name) {
  if (!name) return '未知地面站';
  
  // 清理名称
  const cleanName = name.trim().replace(/\n/g, '');
  
  // 优先从映射表查找
  if (gatewayNameMapping[cleanName]) {
    return gatewayNameMapping[cleanName];
  }
  
  // 如果映射表没有，返回原始名称
  return cleanName;
}

/**
 * 获取简短的中文地面站名称（仅城市名）
 * @param {string} name - 英文名称
 * @returns {string} 中文城市名
 */
export function getChineseCityName(name) {
  if (!name) return '未知';
  
  // 优先从映射表查找
  const cleanName = name.trim().replace(/\n/g, '');
  if (gatewayNameMapping[cleanName]) {
    return gatewayNameMapping[cleanName];
  }
  
  return cleanName;
}

/**
 * 获取国家/州的中文名称
 * @param {string} code - 州代码或国家代码
 * @returns {string} 中文名称
 */
export function getChineseLocationName(code) {
  if (!code) return '未知';
  return code;
}
