export const KNOWN_GATEWAY_COUNTRIES = [
  '美国', '加拿大', '墨西哥', '巴西', '阿根廷', '智利', '哥伦比亚', '秘鲁',
  '英国', '德国', '法国', '西班牙', '意大利', '荷兰', '波兰', '葡萄牙',
  '爱尔兰', '瑞士', '奥地利', '挪威', '瑞典', '丹麦', '芬兰', '比利时',
  '日本', '澳大利亚', '新西兰', '印度尼西亚', '菲律宾', '新加坡', '马来西亚',
  '印度', '孟加拉国', '土耳其', '尼日利亚', '肯尼亚', '南非', '卢旺达',
  '斐济', '莫桑比克',
];

export const POP_COUNTRY_MAPPING = {
  US: '美国',
  AU: '澳大利亚',
  ID: '印度尼西亚',
  BR: '巴西',
  JP: '日本',
  PL: '波兰',
  NG: '尼日利亚',
  CO: '哥伦比亚',
  PE: '秘鲁',
  AR: '阿根廷',
  CL: '智利',
  CA: '加拿大',
  MX: '墨西哥',
  BG: '保加利亚',
  GB: '英国',
  UK: '英国',
  PH: '菲律宾',
  ES: '西班牙',
  DE: '德国',
  NZ: '新西兰',
  QA: '卡塔尔',
  SG: '新加坡',
  IN: '印度',
  KE: '肯尼亚',
  ZA: '南非',
  OM: '阿曼',
  IT: '意大利',
  GT: '危地马拉',
  BD: '孟加拉国',
  FJ: '斐济',
  GU: '关岛',
};

export const CLLI_TO_COUNTRY = {
  STTLWAX1: 'US', CHCOILX1: 'US', DNVRCOX1: 'US', LSANCAX1: 'US',
  NWYYNYX1: 'US', ATLAGAX1: 'US', DLLSTXX1: 'US', MPLSMNX1: 'US',
  ASHNVAX2: 'US', MMMIFLX1: 'US', TMPEAZX1: 'US', SNJECAX1: 'US',
  SLTYUTX1: 'US', KSCYMOX1: 'US',
  CLGYCAN1: 'CA', MNTLCAN1: 'CA',
  QRTOMEX1: 'MX', GTMYGTM1: 'GT', BGTACOL1: 'CO', LIMAPER1: 'PE',
  SNTOCHL1: 'CL', SPLOBRA1: 'BR', FRTABRA1: 'BR', BRSABRA1: 'BR',
  BNSSARG1: 'AR',
  FRNTDEU1: 'DE', MDRDESP1: 'ES', LNDNGBR1: 'GB',
  SFIABGR1: 'BG', WRSWPOL1: 'PL', MLNNITA1: 'IT',
  TKYOJPN1: 'JP', SNGESGP1: 'SG', JTNAIDN1: 'ID', SRBAIND2: 'ID',
  MNLAPH1: 'PH', MMBIIND1: 'IN', DHKABGD1: 'BD',
  DOHAQAT1: 'QA', MSCTOM1: 'OM',
  LGOSNGA1: 'NG', NRBIKEN1: 'KE', JHNGZAF1: 'ZA',
  SYDYAUS1: 'AU', MLBEAUS1: 'AU', BRSEAUS1: 'AU', PRTHAU1: 'AU',
  AKLNZL1: 'NZ', CHRHNZL1: 'NZ',
};
