#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""后端业务错误码定义。"""

# Common
OK = 'OK'
COMMON_INVALID_PARAM = 'COMMON_INVALID_PARAM'
COMMON_NOT_FOUND = 'COMMON_NOT_FOUND'
COMMON_CONFLICT = 'COMMON_CONFLICT'
COMMON_INTERNAL_ERROR = 'COMMON_INTERNAL_ERROR'
COMMON_EXPORT_LIMIT_EXCEEDED = 'COMMON_EXPORT_LIMIT_EXCEEDED'

# Database update
DB_UPDATE_RUNNING = 'DB_UPDATE_RUNNING'
DB_UPDATE_CONFIG_SAVE_FAILED = 'DB_UPDATE_CONFIG_SAVE_FAILED'
DB_UPDATE_EXECUTION_FAILED = 'DB_UPDATE_EXECUTION_FAILED'
DB_UPDATE_INVALID_HOST = 'DB_UPDATE_INVALID_HOST'
DB_UPDATE_INVALID_PORT = 'DB_UPDATE_INVALID_PORT'
DB_UPDATE_MISSING_HOST = 'DB_UPDATE_MISSING_HOST'
DB_UPDATE_MISSING_PASSWORD = 'DB_UPDATE_MISSING_PASSWORD'

# Scan
SCAN_MISSING_IP_SEGMENT = 'SCAN_MISSING_IP_SEGMENT'
SCAN_INVALID_IP_SEGMENT = 'SCAN_INVALID_IP_SEGMENT'
SCAN_REPORT_DIR_MISSING = 'SCAN_REPORT_DIR_MISSING'
SCAN_REPORT_NOT_FOUND = 'SCAN_REPORT_NOT_FOUND'

# Auth & user management
AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED'
AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN'
AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED'
AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED'
AUTH_FORBIDDEN = 'AUTH_FORBIDDEN'
AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND'
AUTH_USER_DISABLED = 'AUTH_USER_DISABLED'
AUTH_LOGIN_INVALID_INPUT = 'AUTH_LOGIN_INVALID_INPUT'
AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED'
AUTH_LOGIN_RATE_LIMITED = 'AUTH_LOGIN_RATE_LIMITED'
AUTH_CHANGE_PASSWORD_INVALID_INPUT = 'AUTH_CHANGE_PASSWORD_INVALID_INPUT'
AUTH_CHANGE_PASSWORD_INVALID_OLD = 'AUTH_CHANGE_PASSWORD_INVALID_OLD'
AUTH_PASSWORD_CHANGE_REQUIRED = 'AUTH_PASSWORD_CHANGE_REQUIRED'
AUTH_RESET_TOKEN_INVALID = 'AUTH_RESET_TOKEN_INVALID'
AUTH_RESET_TOKEN_DELIVERY_NOT_FOUND = 'AUTH_RESET_TOKEN_DELIVERY_NOT_FOUND'
AUTH_RESET_TOKEN_DELIVERY_FORBIDDEN = 'AUTH_RESET_TOKEN_DELIVERY_FORBIDDEN'
AUTH_RESET_TOKEN_DELIVERY_EXPIRED = 'AUTH_RESET_TOKEN_DELIVERY_EXPIRED'
AUTH_RESET_TOKEN_DELIVERY_USED = 'AUTH_RESET_TOKEN_DELIVERY_USED'
AUTH_USER_CREATE_INVALID_INPUT = 'AUTH_USER_CREATE_INVALID_INPUT'
AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS'
AUTH_USER_INVALID_ROLE = 'AUTH_USER_INVALID_ROLE'
AUTH_USER_INVALID_STATUS = 'AUTH_USER_INVALID_STATUS'
AUTH_DELETE_SELF_FORBIDDEN = 'AUTH_DELETE_SELF_FORBIDDEN'
AUTH_UPDATE_SELF_FORBIDDEN = 'AUTH_UPDATE_SELF_FORBIDDEN'
AUTH_LAST_ADMIN_FORBIDDEN = 'AUTH_LAST_ADMIN_FORBIDDEN'
